// Generated by scripts/gen-schema.mjs from db/schema.sql and rubric.txt. Applied automatically on first use.
export const SCHEMA_STATEMENTS: string[] = [
  "create table if not exists roles (\n  workspace      text not null default 'main',\n  key            text not null,\n  title          text not null,\n  tagline        text not null default '',\n  requirements   text not null default '',\n  interview_note text not null default '',\n  shortlist_size integer not null default 5 check (shortlist_size between 1 and 50),\n  sort_order     integer not null default 0,\n  archived       boolean not null default false,\n  created_at     timestamptz not null default now(),\n  constraint roles_ws_pkey primary key (workspace, key)\n)",
  "create table if not exists rubric_criteria (\n  id          uuid primary key default gen_random_uuid(),\n  workspace   text not null default 'main',\n  role        text not null,\n  key         text not null,\n  name        text not null,\n  description text not null,\n  weight      integer not null check (weight between 0 and 100),\n  sort_order  integer not null default 0,\n  constraint rubric_ws_role_key unique (workspace, role, key)\n)",
  "create table if not exists candidates (\n  id               uuid primary key default gen_random_uuid(),\n  workspace        text not null default 'main',\n  created_at       timestamptz not null default now(),\n  applied_role     text not null,\n  file_name        text not null,\n\n  personal_details jsonb not null default '{}'::jsonb,\n\n  cv_text          text,\n\n  status           text not null default 'processing'\n                   check (status in ('processing','scored','error')),\n  error            text,\n\n  scores           jsonb,\n  pm_score         numeric,\n  spm_score        numeric,\n  headline         text,\n\n  brief            text,\n  interview_questions jsonb,\n  draft_type       text check (draft_type in ('invite','rejection')),\n  draft_locked     boolean not null default false,\n  draft_subject    text,\n  draft_body       text,\n\n  email_status     text not null default 'none' check (email_status in ('none','draft','sent','failed')),\n  email_error      text,\n  sent_at          timestamptz,\n  sent_to          text,\n  resend_id        text\n)",
  "create index if not exists candidates_role_pm  on candidates (applied_role, pm_score desc)",
  "create index if not exists candidates_role_spm on candidates (applied_role, spm_score desc)",
  "alter table rubric_criteria drop constraint if exists rubric_criteria_role_check",
  "alter table candidates drop constraint if exists candidates_applied_role_check",
  "alter table roles add column if not exists workspace text not null default 'main'",
  "alter table rubric_criteria add column if not exists workspace text not null default 'main'",
  "alter table candidates add column if not exists workspace text not null default 'main'",
  "do $$ begin if not exists (select 1 from pg_constraint where conname = 'roles_ws_pkey') then alter table roles drop constraint if exists roles_pkey; alter table roles add constraint roles_ws_pkey primary key (workspace, key); end if; end $$",
  "do $$ begin if not exists (select 1 from pg_constraint where conname = 'rubric_ws_role_key') then alter table rubric_criteria drop constraint if exists rubric_criteria_role_key_key; alter table rubric_criteria add constraint rubric_ws_role_key unique (workspace, role, key); end if; end $$",
  "create index if not exists candidates_ws on candidates (workspace, applied_role)",
  "alter table candidates add column if not exists interview_questions jsonb"
];

export const DEFAULT_ROLES = [
  {
    "key": "PM",
    "title": "Product Manager",
    "tagline": "Core platform · 2–4 yrs",
    "sort_order": 0,
    "shortlist_size": 5,
    "interview_note": "a 45-minute conversation with Arjun in Mumbai or on video",
    "requirements": "First PM on Kargo's core operations platform (shipment tracking, documentation workflows, real-time status visibility for freight forwarders). Owns the roadmap, customer discovery and working directly with engineering on what gets built and why. Sets up the rhythms a PM function needs. 2–4 years of product management, comfortable without structure, has shipped and killed things in short cycles, curious about how operations work at ground level. In-office, Mumbai."
  },
  {
    "key": "SPM",
    "title": "Senior Product Manager",
    "tagline": "Integrations & data layer · 5–8 yrs",
    "sort_order": 1,
    "shortlist_size": 5,
    "interview_note": "a 60-minute conversation with Arjun in Mumbai or on video",
    "requirements": "Most senior PM at Kargo, owning the integration and data layer: carrier systems, port portals, ERP environments and freight management tools. Makes the hard architectural product calls (build vs configure vs not touch), sets reliability and data-quality standards, and helps define how the PM function works. 5–8 years of product management with clear evidence of owning an area without senior PMs above, platform/integration experience, early-stage environments, and ground-level familiarity with logistics or supply chain. In-office, Mumbai."
  }
];

export const RUBRIC_ROWS = [
  {
    "role": "PM",
    "name": "Hands-on Operations Time",
    "key": "hands_on_ops",
    "description": "Has personally done operational work in freight, logistics, ports, supply chain or a similarly operations-heavy floor - handled shipments, documentation, carriers, customs or exceptions themselves - for at least a year, and the CV names the specifics (Bills of Lading, CHAs, carrier allocation, berth windows, exception queues). Partial (2-3): built software for operations users, or embedded/visited with them, but never did the work. Weak (0-1): operations knowledge only from software, consulting, or interviews.",
    "weight": 30,
    "sort_order": 0
  },
  {
    "role": "PM",
    "name": "Unasked Builds That Got Adopted",
    "key": "unasked_builds",
    "description": "Noticed a gap nobody assigned them, built a fix on their own initiative (a tracker, prototype, SOP, framework, template or process), and other people adopted it - with the adoption named (e.g. \"adopted by the 12-person team within two weeks\", \"now the team standard\"). Partial (2-3): improvements inside their assigned scope, or self-started builds with no adoption evidence. Weak (0-1): only assigned deliverables.",
    "weight": 25,
    "sort_order": 1
  },
  {
    "role": "PM",
    "name": "Owns the Miss",
    "key": "owns_the_miss",
    "description": "Describes a specific thing that went wrong - a killed feature, a lost deal, an outage, a crisis - and shows they owned it personally and turned it into a fix or a documented lesson others now use (post-mortem shared, feature killed with the data behind it, practice adopted). Partial (2-3): handled a crisis but no lesson captured, or generic \"managed incidents\". Weak (0-1): the CV contains only wins and rising metrics.",
    "weight": 20,
    "sort_order": 2
  },
  {
    "role": "PM",
    "name": "Direct Line to the User",
    "key": "direct_line",
    "description": "Worked face to face with the people who use the work, with no intermediary layer, and changed what got built because of it - e.g. \"no product layer\", embedded with ops teams, primary client contact, and a concrete change that came from it. Partial (2-3): user research through structured interviews, surveys or analytics. Weak (0-1): works through stakeholders and presents roadmaps upward; no direct user contact.",
    "weight": 15,
    "sort_order": 3
  },
  {
    "role": "PM",
    "name": "Makes the Call",
    "key": "makes_the_call",
    "description": "Makes decisions and acts on them quickly without waiting for approval or consensus - killed their own work, redirected capacity, chose a path under pressure - or has a third-party quote about decisiveness. Partial (2-3): executed decisions that others made. Weak (0-1): language centred on \"aligned\", \"socialised\", \"supported\", \"managed stakeholder priorities\".",
    "weight": 10,
    "sort_order": 4
  },
  {
    "role": "SPM",
    "name": "Hands-on Operations Time",
    "key": "hands_on_ops",
    "description": "Two or more years doing operational work themselves (freight, ports, customs, carriers, supply chain) AND at least one example where that ground knowledge shaped a technical, data or integration decision later (e.g. \"designed the integration because I knew what the data actually contained\"). Partial (2-3): hands-on operations time with no link to later product decisions, or under a year of it. Weak (0-1): no hands-on operations time.",
    "weight": 25,
    "sort_order": 0
  },
  {
    "role": "SPM",
    "name": "Unasked Builds That Got Adopted",
    "key": "unasked_builds",
    "description": "Self-initiated builds whose adoption spread beyond their own team - to other teams, other shifts, other branches or the whole company - or became a core product feature. Partial (2-3): self-started builds adopted only within their own team. Weak (0-1): only assigned deliverables.",
    "weight": 15,
    "sort_order": 1
  },
  {
    "role": "SPM",
    "name": "Owns the Miss",
    "key": "owns_the_miss",
    "description": "Owned failure at the level of a product area or function - killed features including their own ideas, reversed a direction on evidence, ran the post-mortem and changed how the team works as a result. Partial (2-3): owned individual incidents or kills without a lasting change to practice. Weak (0-1): only wins and rising metrics.",
    "weight": 20,
    "sort_order": 2
  },
  {
    "role": "SPM",
    "name": "Direct Line to the User",
    "key": "direct_line",
    "description": "Even at a senior level still personally in the room with customers or operators (onboardings, discovery, field visits) with a named decision that came from it. Partial (2-3): contact through their team, research reports or account managers. Weak (0-1): no direct contact at senior level.",
    "weight": 10,
    "sort_order": 3
  },
  {
    "role": "SPM",
    "name": "Makes the Call",
    "key": "makes_the_call",
    "description": "Has owned a product area or function with no senior layer above them for 2+ years, AND made at least one high-consequence, hard-to-reverse call themselves (architecture, build vs configure vs not touch, killing a product line) and lived with the result. Partial (2-3): made calls inside a structure where a senior PM or committee had final say. Weak (0-1): mainly executed or \"aligned\" on others' decisions.",
    "weight": 30,
    "sort_order": 4
  }
];
