-- Generated from rubric.txt by `npm run db:setup`.
delete from rubric_criteria;
insert into rubric_criteria (role, key, name, description, weight, sort_order) values
  ('PM', 'hands_on_ops', 'Hands-on Operations Time', 'Has personally done operational work in freight, logistics, ports, supply chain or a similarly operations-heavy floor - handled shipments, documentation, carriers, customs or exceptions themselves - for at least a year, and the CV names the specifics (Bills of Lading, CHAs, carrier allocation, berth windows, exception queues). Partial (2-3): built software for operations users, or embedded/visited with them, but never did the work. Weak (0-1): operations knowledge only from software, consulting, or interviews.', 30, 0),
  ('PM', 'unasked_builds', 'Unasked Builds That Got Adopted', 'Noticed a gap nobody assigned them, built a fix on their own initiative (a tracker, prototype, SOP, framework, template or process), and other people adopted it - with the adoption named (e.g. "adopted by the 12-person team within two weeks", "now the team standard"). Partial (2-3): improvements inside their assigned scope, or self-started builds with no adoption evidence. Weak (0-1): only assigned deliverables.', 25, 1),
  ('PM', 'owns_the_miss', 'Owns the Miss', 'Describes a specific thing that went wrong - a killed feature, a lost deal, an outage, a crisis - and shows they owned it personally and turned it into a fix or a documented lesson others now use (post-mortem shared, feature killed with the data behind it, practice adopted). Partial (2-3): handled a crisis but no lesson captured, or generic "managed incidents". Weak (0-1): the CV contains only wins and rising metrics.', 20, 2),
  ('PM', 'direct_line', 'Direct Line to the User', 'Worked face to face with the people who use the work, with no intermediary layer, and changed what got built because of it - e.g. "no product layer", embedded with ops teams, primary client contact, and a concrete change that came from it. Partial (2-3): user research through structured interviews, surveys or analytics. Weak (0-1): works through stakeholders and presents roadmaps upward; no direct user contact.', 15, 3),
  ('PM', 'makes_the_call', 'Makes the Call', 'Makes decisions and acts on them quickly without waiting for approval or consensus - killed their own work, redirected capacity, chose a path under pressure - or has a third-party quote about decisiveness. Partial (2-3): executed decisions that others made. Weak (0-1): language centred on "aligned", "socialised", "supported", "managed stakeholder priorities".', 10, 4),
  ('SPM', 'hands_on_ops', 'Hands-on Operations Time', 'Two or more years doing operational work themselves (freight, ports, customs, carriers, supply chain) AND at least one example where that ground knowledge shaped a technical, data or integration decision later (e.g. "designed the integration because I knew what the data actually contained"). Partial (2-3): hands-on operations time with no link to later product decisions, or under a year of it. Weak (0-1): no hands-on operations time.', 25, 0),
  ('SPM', 'unasked_builds', 'Unasked Builds That Got Adopted', 'Self-initiated builds whose adoption spread beyond their own team - to other teams, other shifts, other branches or the whole company - or became a core product feature. Partial (2-3): self-started builds adopted only within their own team. Weak (0-1): only assigned deliverables.', 15, 1),
  ('SPM', 'owns_the_miss', 'Owns the Miss', 'Owned failure at the level of a product area or function - killed features including their own ideas, reversed a direction on evidence, ran the post-mortem and changed how the team works as a result. Partial (2-3): owned individual incidents or kills without a lasting change to practice. Weak (0-1): only wins and rising metrics.', 20, 2),
  ('SPM', 'direct_line', 'Direct Line to the User', 'Even at a senior level still personally in the room with customers or operators (onboardings, discovery, field visits) with a named decision that came from it. Partial (2-3): contact through their team, research reports or account managers. Weak (0-1): no direct contact at senior level.', 10, 3),
  ('SPM', 'makes_the_call', 'Makes the Call', 'Has owned a product area or function with no senior layer above them for 2+ years, AND made at least one high-consequence, hard-to-reverse call themselves (architecture, build vs configure vs not touch, killing a product line) and lived with the result. Partial (2-3): made calls inside a structure where a senior PM or committee had final say. Weak (0-1): mainly executed or "aligned" on others'' decisions.', 30, 4);
