// Regenerates lib/schema.ts from db/schema.sql and rubric.txt: `node scripts/gen-schema.mjs`
import fs from "node:fs";
import { readRubric } from "./parse-rubric.mjs";

const rows = readRubric();
const schema = fs.readFileSync(new URL("../db/schema.sql", import.meta.url), "utf8")
  .split(/;\s*$/m).map((s) => s.replace(/^\s*--.*$/gm, "").replace(/\s+--[^\n]*$/gm, "").trim()).filter(Boolean);

const roles = [
  {
    key: "PM", title: "Product Manager", tagline: "Core platform · 2–4 yrs", sort_order: 0, shortlist_size: 5,
    interview_note: "a 45-minute conversation with Arjun in Mumbai or on video",
    requirements: "First PM on Kargo's core operations platform (shipment tracking, documentation workflows, real-time status visibility for freight forwarders). Owns the roadmap, customer discovery and working directly with engineering on what gets built and why. Sets up the rhythms a PM function needs. 2–4 years of product management, comfortable without structure, has shipped and killed things in short cycles, curious about how operations work at ground level. In-office, Mumbai.",
  },
  {
    key: "SPM", title: "Senior Product Manager", tagline: "Integrations & data layer · 5–8 yrs", sort_order: 1, shortlist_size: 5,
    interview_note: "a 60-minute conversation with Arjun in Mumbai or on video",
    requirements: "Most senior PM at Kargo, owning the integration and data layer: carrier systems, port portals, ERP environments and freight management tools. Makes the hard architectural product calls (build vs configure vs not touch), sets reliability and data-quality standards, and helps define how the PM function works. 5–8 years of product management with clear evidence of owning an area without senior PMs above, platform/integration experience, early-stage environments, and ground-level familiarity with logistics or supply chain. In-office, Mumbai.",
  },
];

fs.writeFileSync(new URL("../lib/schema.ts", import.meta.url),
  "// Generated by scripts/gen-schema.mjs from db/schema.sql and rubric.txt. Applied automatically on first use.\n" +
  "export const SCHEMA_STATEMENTS: string[] = " + JSON.stringify(schema, null, 2) + ";\n\n" +
  "export const DEFAULT_ROLES = " + JSON.stringify(roles, null, 2) + ";\n\n" +
  "export const RUBRIC_ROWS = " + JSON.stringify(rows, null, 2) + ";\n");
console.log(schema.length, "statements,", roles.length, "roles,", rows.length, "criteria");
